data_loader:
  data_directory: "datasets/train/"
  keep_columns: ["main_deflector_parameters_theta_E",
    "main_deflector_parameters_gamma1",
    "main_deflector_parameters_gamma2",
    "main_deflector_parameters_gamma",
    "main_deflector_parameters_e1",
    "main_deflector_parameters_e2",
    "main_deflector_parameters_center_x",
    "main_deflector_parameters_center_y",
    "source_parameters_center_x",
    "source_parameters_center_y"
    ]

feature_extractor:
  output_dim: 128
  pretrained: false
  
posterior_estimator:
  density_estimator: "maf"  
  z_score_theta: none
  z_score_x: none
  hidden_features: 128  
  num_transforms: 5
  num_components: 1
  num_bins: 10

training:
  batch_size: 200
  learning_rate: 5e-4
  validation_fraction: 0.1
  stop_after_epochs: 20
  max_num_epochs: 2**31 - 1
  resume_training: false
  retrain_from_scratch: false

model_directory: "models/"